### PR TITLE
Fix bus monitor mode

### LINKED ISSUE #13: IP gateway bus monitor mode stops after first telegram
Hello, after receiving the first telegram in bus monitor mode with a KNX/EIB IP gateway the connection closes because knxmap receives a `KnxDisconnectRequest`. The bus monitor mode is supported by the gateway. Is there anything I can do about this and keep the connection alive? The group monitor works perfectly fine though.

The command I'm executing is the following: `knxmap monitor <ip>`

//edit: I'm testing on Debian 9 64bit with python 3.6.6

### PR DESCRIPTION
**Pull request by MaxXor**
Fixes #13

### CODE REVIEW

**Comment by takeshixx** [comment]
Thank you very much for creating the issue and submitting the PR! :relieved:

**Comment by MaxXor** [comment]
No problem, thanks for your project.

**Comment by MaxXor** [comment]
Is `develop` branch safe to use?

**Comment by takeshixx** [comment]
It should be, mostly. I just use the develop branch as a playground when I implement and test new features and merge it regularly to master when stuff is working.

**Pull request merged**
